name: First Workflow
on : workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Github Action
        run: echo "This is first workflow in Github Actions"
      - name: Another Github Action
        run: echo "Another Github Action"
  
