name: Second WorkFlow
on: workflow_dispatch
jobs:
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Seond First Step
        run: echo " Second First Step"
      - name: Second Second Step
        run: echo "Second Second Step"
  

  
