name: third workflow
on: push
jobs:
  Third job one:
    runs-on: ubuntu-latest
    steps:
    - name: Third First step
      run: echo "Third First setp"
    - name: Third Second Step
      run: ehco "Third Second step"